config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:new, :create, :show]

  resources :concerts do
    resources :attendances, only: [:new, :create]
  end

  resources :concerts do
    resources :itineraries, only: [:new, :create, :show,:destroy]
  end

  resources :itineraries

  resources :sessions, only: [:new, :create, :destroy]

    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    get '/logout', to: 'sessions#destroy'

    delete '/users/:user_id', to: "itineraries#destroy"
    post '/users/:user_id', to: "itineraries#update"


    post '/concerts/:concert_id', to: "attendances#create"

    root 'concerts#index'




end


##TODO
##PROTECT ROUTES ON EDIT AND DELETE FROM INT SHOW AND USER SHOW !@!!!!!
##Fix edit form so that it presents current values
##Fix itineraries show from a style standpoint


##API
##limit data
##find a way to get it in a service object
##clean up ill be there button

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :attendee, class_name: "User"
  belongs_to :concert
end

app/models/concert.rb
class Concert < ApplicationRecord
  has_many :attendances
  has_many :attendees, through: :attendances, source: :attendee

  def grab_ids
    self.attendees.pluck(:id)
  end

  def upcoming?
    self.date > DateTime.now
  end

##FOR LATER DATETIME
  # def todays_event?
  #   self.starts_ > Time.zone.now.beginning_of_day && self.starts_at < Time.zone.now.end_of_day
  # end
end

app/models/itinerary.rb
class Itinerary < ApplicationRecord
  belongs_to :attendee, class_name: "User", optional: true
  belongs_to :concert, optional: true
  has_many :ratings
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :concert, optional: true
  belongs_to :itinerary, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :itineraries
  has_many :attendances
  has_many :attended_concerts, through: :attendances, source: :concert

  validates :first_name, :last_name, :email, :password_digest, presence: true
  validates :email, uniqueness: true
  validates_format_of :email,:with => /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include ApplicationHelper
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController

  def new
    @attendance = Attendance.new
  end


  def create
    @attendance = Attendance.new
    @concert = Concert.find_by(id: params[:id])

    @attendance.attendee_id = current_user.id
    @attendance.concert_id = params[:concert_id]

    if @attendance.save
      redirect_to concert_path(params[:concert_id])
    else
      @errors = @attendance.errors.full_messages
      render :show
    end
  end



  def destroy
  end

end

app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController

  before_action :redirect_unless_logged_in, except: [:index, :show]

  def index
    @concerts = Concert.all.order(:date)
    @upcoming_concerts = @concerts.select {|concert| concert.upcoming?}
  end

  def show
    @concert = Concert.find_by(id: params[:id])
    # @songs = AppleResponse.grab_songs(@concert.band)
    @songs = grab_songs(@concert.band)
    render :show
  end

  def new
  end

  def create
  end



end

app/controllers/itineraries_controller.rb
class ItinerariesController < ApplicationController

  before_action :redirect_unless_logged_in


  def new
    @itinerary = Itinerary.new
    @concert = Concert.find(params[:concert_id])
    render 'itineraries/new'
  end

  def create
    @itinerary = Itinerary.new(itinerary_params)
    @concert = Concert.find(params[:concert_id])

    @itinerary.attendee_id = current_user.id
    @itinerary.concert_id = params[:concert_id]


    if @itinerary.save
       current_user.itineraries << @itinerary
       redirect_to user_path(current_user.id)
    else
      @errors = @itinerary.errors.full_messages
      render :new
    end
  end

  def update
    # raise params.inspect
    @itinerary = Itinerary.find_by(:id => params[:id])
    p @itinerary

    if @itinerary.update(itinerary_params)
      redirect_to itinerary_path(@itinerary)
    else
      @errors = @itinerary.errors.full_messages
      render :edit
    end
  end


  def show
    @itinerary = Itinerary.find_by(:id => params[:id])
  end


  def destroy
    @itinerary = Itinerary.find_by(:id => params[:id])
    @itinerary.destroy
    redirect_to user_path(current_user.id)
  end

  private

  def itinerary_params
    params.permit(:name, :hotel, :flight_info, :arrival_date, :return_date)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      @errors = ["Something went wrong. Please try again"]
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      @errors = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find_by(:id => params[:id])
    @itineraries = Itinerary.all
    @users = Itinerary.pluck(:attendee_id)
    render :show
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end


end

app/helpers/application_helper.rb
require 'net/http'

module ApplicationHelper

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    session[:user_id] != nil
  end

  def redirect_unless_logged_in
    redirect_to new_session_path unless logged_in?
  end

  def redirect_unless_owner(user)
    redirect_to root_path unless current_user == user
  end

  def authorized?(user)
    current_user == user
  end


  def set_time(time)
    time.strftime("at %l:%M %P")
  end

  def set_date(date)
    date.strftime("%m/%d/%y")
  end

  def pretty_date(date)
    date.strftime("%B %dth '%y")
  end

  # def grab_songs
  #   base_url = "https://itunes.apple.com/search?term=phish"
  #   resp = Net::HTTP.get_response(URI.parse(base_url))
  #   buffer = resp.body
  #   result = JSON.parse(buffer)
  #   p "*************"
  #   songs = result["results"]
  #   songs.map {|data| data["trackName"]}
  # end

  def grab_songs(band)
    ##grab base link for api endpoint and pass in band name
    base_url = "https://itunes.apple.com/search?term=#{band}"
    p base_url
    ##create get response object and pass in url
    resp = Net::HTTP.get_response(URI.parse(base_url))
    buffer = resp.body
    result = JSON.parse(buffer)
    ##take response and carve out JSON objs
    p "*************"
    songs = result["results"]
    ##traverse down and map over to get desired results
    songs.map {|data| data["trackName"]}
  end


end

app/views/concerts/_attendee.html.erb
<div class="attendee-list"><%= attendee.first_name %></div>
                  ------------

app/views/concerts/_concert.html.erb
<strong><%= link_to concert.band, concert_path(concert) %></strong> | <%= concert.venue %> | <%= concert.location %>  <%= set_date(concert.date) %> | <%= set_time(concert.start_time) %>

app/views/concerts/_details.html.erb
<h1 class="band-title">
  <%= @concert.band %> - <%= @concert.venue %>
</h1>

app/views/concerts/index.html.erb
<h2 class="concert-header">Upcoming Shows:</h2>

<div class="concert-show-box">
  <ul>
      <% @concerts.each do |concert| %>
       <li><%= render partial: 'concert', locals: {concert: concert} %></li>
      <% end %>
  </ul>
</div>

app/views/concerts/show.html.erb
<div>
  <%= render partial: 'details' %>
</div>


<div class="concert-deetz">
  <ul>
   <dt>Location: <%= @concert.location %></dt><br>
   <dt>Date: <%= set_date(@concert.date) %></dt><br>
   <dt>Time: <%= set_time(@concert.start_time) %></dt><br>
  </ul>
</div>


<h2 class="attendee-header">Who is all going?</h2>

<div class="attendee-list">
  <ul>
    <dt><%= render partial: 'attendee', collection: @concert.attendees %></dt>
  </ul>
</div>

<div class="add-attendee">
  <% if logged_in? && !@concert.grab_ids.include?(current_user.id) %>
      <%= form_tag [@concert, @attendance], url: concert_attendances_path(@concert),  method: 'POST', id: "attendee-form" do |t| %>
        <%= submit_tag "I'll be there!" %>
    <% end  %>
  <% end %>
</div>

<h1 class="itinerary-new-header">Going? Make it offical!: </h1>

<div class="add-itinerary">
  <p><%= link_to "Add Trip", new_concert_itinerary_path(@concert) %></p>
</div>


<div class="songs">
  <h3>Epic Tracks:</h3>
  <ul>
    <% @songs.each do |song| %>
      <dt><%= song %></dt>
  <% end %>
  </ul>
</div>

app/views/itineraries/_edit.html.erb
  <div class="edit-form">
    <p>
      <%= form_tag @itinerary_path, :method => "PATCH" do |f| %>
    </p>

    <p>
      <strong>Trip Name:</strong><br>
      <%= text_area_tag :name %>
    </p>

    <p>
      <strong>Hotel/Lodging:</strong><br>

      <%= text_area_tag :hotel %>
    </p>

    <p>
      <strong>Flight Information:</strong><br>
      <%= text_area_tag :flight_info %>
    </p>

    <p>
      <strong>Arrival Date:</strong><br>
      <%= date_field_tag(:arrival_date, Date.today)%>
    </p>

    <p>
      <strong>Return Date:</strong><br>
      <%= date_field_tag(:return_date, Date.today)%>
    </p>

    <p>
      <%= submit_tag "Edit Itinerary" %>
    </p>
    <% end %>
  </div>

app/views/itineraries/_form.html.erb
<div class="new-int-form">
  <%= render partial: 'shared/errors', locals: {errors: @errors} if @errors %>
  <p>
    <%= form_tag [@concert, @itinerary], url: concert_itineraries_path(@concert), method: "POST" do |f| %>
    </p>

    <p>
      <strong>Trip Name:</strong><br>
      <%= f.label :name %>
      <%= text_area_tag :name %>
    </p>

    <p>
      <strong>Hotel/Lodging:</strong><br>
      <%= f.label :hotel %>
      <%= text_area_tag :hotel %>
    </p>

    <p>
      <strong>Flight Information:</strong><br>
      <%= f.label :flight_info %>
      <%= text_area_tag :flight_info %>
    </p>

    <p>
      <strong>Arrival Date:</strong><br>
      <%= f.label :arrival_date %>
      <%= date_field_tag(:arrival_date, Date.today)%>
    </p>

    <p>
      <strong>Return Date:</strong><br>
      <%= f.label :return_date %>
      <%= date_field_tag(:return_date, Date.today)%>
    </p>

    <p>
      <%= submit_tag "Save Itinerary" %>
    </p>

  <% end  %>
</div>

app/views/itineraries/_itinerary.html.erb
  <h2 class="trip-name"><%= @itinerary.name %></h2>
  <dt>
      at:
      <strong class='location'><%= @itinerary.concert.venue %> - <%= @itinerary.concert.location %></strong>
      <p>Hotel:</p>
        <%= @itinerary.hotel %>
      <p>Flight Info:</p>
        <%= @itinerary.flight_info %>
      <p>Arrival Date:</p>
        <%= pretty_date(@itinerary.arrival_date) %>
      <p>Return Date:</p>
        <%= pretty_date(@itinerary.return_date) %>
  </dt>

app/views/itineraries/new.html.erb
<h1 class="new-int-header">Going to see <%= @concert.band %> at <%= @concert.venue %>?</h1>


<div class="new-int-form">
  <%= render partial: 'shared/errors', locals: {errors: @errors} if @errors %>
  <p>
    <%= form_tag [@concert, @itinerary], url: concert_itineraries_path(@concert), method: "POST" do |f| %>
    </p>

    <p>
      <strong>Trip Name:</strong><br>
      <%= text_area_tag :name %>
    </p>

    <p>
      <strong>Hotel/Lodging:</strong><br>
      <%= text_area_tag :hotel %>
    </p>

    <p>
      <strong>Flight Information:</strong><br>
      <%= text_area_tag :flight_info %>
    </p>

    <p>
      <strong>Arrival Date:</strong><br>
      <%= date_field_tag(:arrival_date, Date.today)%>
    </p>

    <p>
      <strong>Return Date:</strong><br>
      <%= date_field_tag(:return_date, Date.today)%>
    </p>

    <p>
      <%= submit_tag "Save Itinerary" %>
    </p>

  <% end  %>
</div>

app/views/itineraries/show.html.erb
<div class="itinerary-show">
  <%= render 'itinerary' %>
</div>

<div>
  <h1 align="center">Edit your ShowTrip</h1>
    <p><%= button_to "Delete Trip", @itinerary, method: :delete %></p>
      <%= render 'edit' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShowTrips</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link href="https://fonts.googleapis.com/css?family=Anton|Archivo+Black|Open+Sans|Pangolin|Roboto" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato|Lobster|Open+Sans|Oswald|Permanent+Marker" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  </head>

  <body>

  <nav class="login-bar">
    <% if current_user %>
       Signed in as <%= current_user.first_name %> | <%= link_to "Logout", logout_path %>
         <%= link_to "Your Trips", user_path(current_user) %>
     <% else %>
       <%= link_to 'Login', login_path %> | <%= link_to 'Signup', new_user_path %>
    <% end %>
  </nav>

    <div class="top-nav">

        <nav class="main-nav">
          <ul>
            <li><%= link_to "Home", root_path %></li>
          </ul>
        </nav>

        <nav class="category">
          <ul>
           <li>Contact the Developer:</li>
            <li><a href="https://twitter.com/mitchell_sean35">Twitter</a></li>
           | <li><a href="https://www.linkedin.com/in/mitch-mele-823643b5/"> Linkedin</a></li>
           | <li><a href="https://github.com/msmele345">Github</a></li>
          </ul>
        </nav>
    </div>
  <h1 class="layout-header">ShowTrips</h1>

    <%= yield %>
  </body>
</html>

app/views/shared/_errors.html.erb
<ul>
  <% @errors.each do |error| %>
    <li><%= error %></li>
  <% end  %>
</ul>

app/views/users/new.html.erb
<h2 align="center">Sign up!</h2>

<div class="user-login">
  <%= render 'shared/errors', locals: {errors: @errors} if @errors %>
  <%= form_for @user do |user| %>
    <%= user.text_field :first_name, placeholder: "First Name" %><br><br>
    <%= user.text_field :last_name, placeholder: "Last Name" %><br><br>
    <%= user.text_field :email, placeholder: "Email" %><br><br>
    <%= user.password_field :password, placeholder: "password" %><br><br>
    <%= user.submit "Register"  %>

  <% end  %>
</div>

app/views/users/show.html.erb
<h1 class="user-show-header">
  <%= @user.first_name %> 's upcoming trips:
</h1>


<div class="user-show-box">
  <% if logged_in? && @users.include?(current_user.id) %>
  <ul>
      <% @itineraries.each do |trip| %>
    <dt>
      <h2 class="trip-name">
        <%= trip.name %>
      </h2>
      at:
      <strong class='location'><%= trip.concert.venue %> - <%= trip.concert.location %></strong>
      <p>Hotel:</p>
        <%= trip.hotel %>
      <p>Flight Info:</p>
        <%= trip.flight_info %>
      <p>Arrival Date:</p>
        <%= pretty_date(trip.arrival_date) %>
      <p>Return Date:</p>
        <%= pretty_date(trip.return_date) %>
      <p><%= link_to "Edit Trip", "/itineraries/#{trip.id}" %></p>
    </dt>

      <% end %>
  </ul>
  <% end %>
</div>